# Generated by Django 3.2.7 on 2021-09-27 18:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('4ace17d5-2853-46d3-b1e8-07713e67afd7'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
    ]
